test:sort01.o sort01_print.o sort01_swap.o
  gcc -o test sort01.c sort01_print.c sort01_swap.c

sort01.o: sort01.c
  gcc -c sort01.c

sort01_print.o: sort01_print.c
  gcc -c sort01_print.c

sort01_swap.o: sort01_swap.c
  gcc -c sort01_swap.c
